name: snyk-container-scan

trigger: none

parameters:
  - name: snykOrg
    type: string
    default: 'bdhp-automation-test'
  - name: imagelistVersion
    type: string
    default: ''

variables:
  SNYK_SEVERITY: 'high'
  dockerRegistryServiceConnection: 'BDHP Container Registry-$(System.TeamProject)'

stages:
- stage: snykScan
  jobs:
  - job: scanJob
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '16.x'
      displayName: 'Install Node.js'

    - script: npm install -g snyk
      displayName: 'Install Snyk CLI'

    - script: snyk auth $(SNYK_TOKEN)
      displayName: 'Authenticate Snyk CLI'

    - task: Docker@2
      displayName: 'Docker Login to ACR'
      inputs:
        command: login
        containerRegistry: ${{ variables.dockerRegistryServiceConnection }}

    - template: templates/download-image-list.yml
      parameters:
        imagelistVersion: ${{ parameters.imagelistVersion }}

    - template: templates/run-snyk-scan.yml
      parameters:
        snykOrg: ${{ parameters.snykOrg }}
